### ISSUE TITLE
Propagate repeatable forms to additional glyphs

### ISSUE THREAD

**Issue by n8willis** [theseunbadejo/nsibidi-libre#10]
Related to #7 is that you still have several letterforms that you could create just by building from what you already have:
- p and q from b/d
- c from e/o
- y and w from v
- j and l from i

Similarly in the capitals. In the decorated/morph version, there may (of course) be a lot of distinctions that mean those glyphs can't remain as similar, but it will help testing and spacing in particular if you go for it and create those now in the plain version.

Something you might consider is building those, then putting a different highlight/background color on them in the Font view in Glyphs. That way you don't forget that they are "inheriting" their shapes and may be placeholders not final designs.

**Comment by theseunbadejo** [comment]
Thanks for this @n8willis. I made updates to the lowercase letters, I am working on the Uppercase letters next and should have a complete alphabet before the end of the week
<img width="2472" alt="Screenshot 2023-12-05 at 5 50 10 PM" src="https://github.com/theseunbadejo/nsibidi-libre/assets/47482372/33be2006-b75c-4dc5-946b-cbae017f2259">
<img width="1425" alt="Screenshot 2023-12-05 at 5 52 53 PM" src="https://github.com/theseunbadejo/nsibidi-libre/assets/47482372/865e27f6-d8c8-4926-b110-e85bac86e147">
