### ISSUE TITLE
Need a different name for the font

### ISSUE THREAD

**Issue by tphinney** [theseunbadejo/nsibidi-libre#11]
So, I know that the decorative elements of the font are inspired by Nsibidi, BUT  Nsibidi is of course the name for a system of written pictograms, which is encoded in Unicode. So really any font with Nsibidi in the name will be expected to support those characters. As this typeface does not, I don’t think we can get away with calling it Nsibidi Libre.

Somebody in the audience brought this up when I presented it, and other African Latin fonts in development, at the Face/Interface conference at Stanford two days ago.

**Comment by n8willis** [comment]
Good to know. Just for the sake of maximum clarity, is the note that "the font name should not include `Nsibidi`" or just that the font name needs to include something in addition to it?

**Comment by tphinney** [comment]
I would think “should not include”—but if somebody has an idea for a name that includes “Nsibidi” but makes the relationship clear, I am open to other ideas.

**Comment by theseunbadejo** [comment]
Thanks for bringing this to my attention @tphinney .

I did a bit of research and figured I could rename the font either;

1. Nsibidi Forma

"Forma" (Latin for shape or form), this name indicates that the typeface is inspired by the shapes and forms of Nsibidi pictographs.

or 

2. Ekoi Display

"Ekoi" is another name for the Ejagham people (the original owners of Nsibidi), which could lend its name to the typeface.

Nsibidi Forma would be my first choice if it works and if it does not, we can stick with Ekoi Display.

**Comment by tphinney** [comment]
I would be inclined to think Ekoi Display is a less potentially confusing choice.

**Comment by theseunbadejo** [comment]
I agree @tphinney.

I took some more time to think about it and I think "Ekoi NSBD" could work. 

I added the NSBD so the relationship between the typeface and Nsibidi is clear. plus it's not fully spelt so I don't know if that would be a problem.

I just really want it to be clear that the forms were derived from Nsibidi.

**Comment by tphinney** [comment]
Hmmm. I *guess* that would be ok? @davelab6 do you have any opinion?

**Comment by theseunbadejo** [comment]
Hi everyone, I stumbled across a perfect name today during my research on renaming my masters.

I present..

*drumroll*

"Áká Ágụ́ Display" which translates to "Leopard Hand Display", I think it is spot on and would serve to pay homage to work peviously done by others studying Nsibidi.

<img width="1045" alt="Screenshot 2024-03-10 at 1 44 25 PM" src="https://github.com/theseunbadejo/nsibidi-libre/assets/47482372/db691a2a-82df-4c42-9894-d3e17ecdcde5">

I would like to know what you all think about this. @davelab6 @tphinney @n8willis

**Comment by n8willis** [comment]
It's distinctive, which is great!

The one wrinkle, as a purely practical matter, is that all the font families served by the Google Fonts servers can only use family names with basic/un-accented letters in them. I suspect (but don't know for sure) that this is a restriction that makes it easier for people using the API and CSS markup, etc.

So you'd have to make personal peace with that appearing as Aka Agu Display *in* the font catalog pages. Although: you could still be sneaky and put the accented version of the name in your artwork and masthead on GitHub, on font minisite material, and so on. Maybe even in the paragraph describing the background and goals of the font.

But you'd want to get readers prepared for the ASCII-only version by sticking to the plain version in your repo name and the main catalog text — i.e., in the places where you talk specifically about the font-as-they-can-use-it.

Or that's my take anyway.

**Comment by tphinney** [comment]
Just so.

Also there are some older desktop environments in which accented names in font menus break things. When I was at Adobe, back in 2001 we shipped Orgánica, and right afterwards had to change the font menu name to be unaccented, because it did bad things in Word (on at least one platform). I am sure Microsoft fixed that, but not instantly.  :/

**Comment by theseunbadejo** [comment]
An update on naming, I spoke with Jordan and Favour, who are both working with me to help advice on Nsibidi translations and copy respectively and we landed on the name "Agu Display" as opposed to "Aka Agu" it means Leopard and is a nod to the secret societies that use Nsibidi, We have been able to weave this into the storytelling and it is looking great so far.

**Comment by davelab6** [comment]
Sounds good to me

**Comment by davelab6** [comment]
Please close
