### ISSUE TITLE
Numerals

### ISSUE THREAD

**Issue by n8willis** [theseunbadejo/nsibidi-libre#13]
1 - the base on 1 needs to be longer, so that supports / looks like it's under the "arm" on the top right.

Heights - it's usually a good idea to pick a slightly shorter "number height" than is used for the capital height; that helps prevent confusion between O and 0, but it also makes a long sequence of numbers like a phone number not stick out from the page so much when it's in a sentence.

Spacing - the numerals will need 'tabular' spacing. When all the designs are done, take the widest form (not including its sidebearings), set out a whole row full of just that, then adjust the sidebearings until they look about as equal as a similar test line of HHH or OOO or HOHO or whatever. Then, the total width of that numeral has to be the total width for all the others.

**Comment by theseunbadejo** [comment]
Thanks a lot for this Nate, I have fixed this and would share it in my latest commit. 

I also did a bit of testing to check if my O and 0 could be mistaken for each other and they look quite distinct at the moment.

**Comment by n8willis** [comment]
So, the shapes here are looking good, but you should also regularize the heights of the numerals.

Currently, `1`, `2`, and `3` are taller than the others. (700 vs 670 for the rest).

Should be a simple adjustment to make them all the same. But do also make optical adjustments to the  numeral forms where there is a round or a pointed angle at the top or bottom: those should get a small overshoot or undershoot, just like round or pointed-angle letters do.

As for what the correct height is for the numerals ... you have flexibility to choose there. Often the choice is to make numerals slightly shorter than capital-height letters — which is another technique that can help differentiate the zero from the "O" and "o".

**Comment by theseunbadejo** [comment]
Thank you for raising this issue @n8willis I resolved it a few commits ago and all the numerals are the appropriate height now.
