### ISSUE TITLE
Vietnamese review

### ISSUE THREAD

**Issue by crystaltype** [theseunbadejo/nsibidi-libre#20]
Hello @theseunbadejo, here are my design suggestions for Vietnamese :)
Overall you did a very awesome job! I only have some small suggestions.
- [x] General design of accents & position
![Screenshot_2024-04-30_at_16 22 33](https://github.com/theseunbadejo/nsibidi-libre/assets/20129845/373e3555-b25b-46da-8ee0-a68e48883e75)
![Screenshot_2024-04-30_at_16 23 42](https://github.com/theseunbadejo/nsibidi-libre/assets/20129845/68ee626f-ba5c-4c1e-b070-036f4bd22cba)
![Screenshot_2024-04-30_at_16 27 00](https://github.com/theseunbadejo/nsibidi-libre/assets/20129845/92aab731-0d45-4ab2-bb03-8aca55d060a8)
![Screenshot_2024-04-30_at_16 43 00](https://github.com/theseunbadejo/nsibidi-libre/assets/20129845/05a3b4de-a3c4-4697-90a7-5488fd9fc202)
![Screenshot_2024-04-30_at_16 43 26](https://github.com/theseunbadejo/nsibidi-libre/assets/20129845/36b12d1f-dfb6-424d-86a1-941e77d7a437)
- [x] Horn design improvement
![Screenshot_2024-04-30_at_16 44 36](https://github.com/theseunbadejo/nsibidi-libre/assets/20129845/a9516afc-c8a0-42fa-98a1-aa285c42a2dc)
- [x] Crossbar of dcroat
![Screenshot_2024-04-30_at_16 45 06](https://github.com/theseunbadejo/nsibidi-libre/assets/20129845/d4e1e419-b260-4537-a996-6be561569c27)
- [x] General design of accents & position
![Screenshot_2024-04-30_at_16 45 27](https://github.com/theseunbadejo/nsibidi-libre/assets/20129845/d7da2dba-8ea4-4b77-bf50-482595e2e79d)

**Comment by crystaltype** [comment]
Also here is the general resource I've been working on recently. They're all possible Vietnamese combination, feel free to use it to check for problematic kerning pairs :)

[possible_Vietnamese_combination_capitalized.txt](https://github.com/user-attachments/files/15849133/possible_Vietnamese_combination_capitalized.txt)

[possible_Vietnamese_combination.txt](https://github.com/user-attachments/files/15849132/possible_Vietnamese_combination.txt)

**Comment by theseunbadejo** [comment]
Thanks a lot for your feedback @crystaltype I have made the updates to all the tasks you mentioned and tested with proofs as well.
