### ISSUE TITLE
Glyphset tracking

### ISSUE THREAD

**Issue by n8willis** [theseunbadejo/nsibidi-libre#21]
This is a quick list of the glyphs that, at present, have skeleton forms but are still needing final decorations in one or more of the masters. Hopefully the list will be useful to identify any characters that could use a language consultant, or any that for some reason aren't actually in the required glyphset for GF, but appear in the grid within Glyphs....

Uppercase:
Ɛ
Ɂ
Ɥ
Ɩ
Ʝ
Ƙ
Ƞ
Ɔ
Ƭ
Ɣ
Ʋ
Ƴ
Ꞌ

Lowercase:
æ
ɓ
ꭓ
ɗ
ʃ
ɣ
ɠ
ʔ
ʕ
ɂ
ɦ
ɩ
ȷ
ʝ
ƙ
ƛ
ɬ
ƞ
ƥ
þ
ɋ
ɾ
ß
ƭ
ʈ
ʋ
ⱳ
ƴ
ꞌ

**Comment by theseunbadejo** [comment]
Thanks a lot for this @n8willis I have updated all these characters with decorations.
