### ISSUE TITLE
Spacing and Proportions

### ISSUE THREAD

**Issue by theseunbadejo** [theseunbadejo/nsibidi-libre#9]
Agyei mentioned refining the spacing on the following characters in my V1.0.6 Proof: 

- e, v, g (right).

and also, to refine the proportions on my "v" as well. 

I would be looking out for the "ives", "eaves", "ge" and "gu" strings.

**Comment by n8willis** [comment]
Yeah, you can take lots of advantage of similarity between shapes in spacing. The right side of your g is straight, so give it the same right sidebearing as n. v is symmetrical, so it should have the same sidebearings on its left and its right, that sort of thing.

I see in the cap C that you've taken advantage of Glyphs's ability to pin the sidebearing of one letter to another; I suggest you go through and do that to everything you can (but look out for things like your e, which are round normally, but have an extending stroke that's part of the design.)

**Comment by n8willis** [comment]
Actually, the "Type Tricks" book by Sophie Beier has tables that show some generic rules for that stuff; you can put those in and reduce the number of glyphs that you are manually adjusting considerably.

For the adjustments, like the left sidebearing on e, Glyphs allows you to put in arithmetic, too, so take advantage of that: https://glyphsapp.com/learn/spacing (down at the "Sidebearing arithmetic" subsection header).
